<?php

namespace App\Helpers;

class CurrencyHelper
{
    public static function mapCurrencyToCountry($currencyCode)
    {
        $currencyCountryMapping = [
            "USD" => 'us',
            "EUR" => 'eu',
            "AUD" => 'au',
            "AED" => 'ae',
            "JPY" => 'jp',
            "CNY" => 'cn',
            "SAR" => 'sa',
            "KRW" => 'kr',
            "INR" => 'in',
            "RUB" => 'ru',
            "AFN" => 'af',
            "ARS" => 'ar',
            "AWG" => 'aw',
            "AZN" => 'az',
            "BSD" => 'bs',
            "BBD" => 'bb',
            "BDT" => 'bd',
            "BYN" => 'by',
            "BZD" => 'bz',
            "BMD" => 'bm',
            "BOB" => 'bo',
            "BAM" => 'ba',
            "BWP" => 'bw',
            "BGN" => 'bg',
            "BRL" => 'br',
            "BND" => 'bn',
            "KHR" => 'kh',
            "CAD" => 'ca',
            "KYD" => 'ky',
            "CLP" => 'cl',
            "COP" => 'co',
            "CRC" => 'cr',
            "HRK" => 'hr',
            "CUP" => 'cu',
            "CZK" => 'cz',
            "DKK" => 'dk',
            "DZD" => 'dz',
            "DOP" => 'do',
            "EGP" => 'eg',
            "GTQ" => 'gt',
            "GHS" => 'gh',
            "HKD" => 'hk',
            "HUF" => 'hu',
            "IDR" => 'id',
            "IRR" => 'ir',
            "ILS" => 'il',
            "LBP" => 'lb',
            "MAD" => 'ma',
            "MYR" => 'my',
            "MVR" => 'mv',
            "NGN" => 'ng',
            "NPR" => 'np',
            "NOK" => 'no',
            "OMR" => 'om',
            "PKR" => 'pk',
            "PHP" => 'ph',
            "PLN" => 'pl',
            "RON" => 'ro',
            "ZAR" => 'za',
            "LKR" => 'lk',
            "SEK" => 'se',
            "SGD" => 'sg',
            "CHF" => 'ch',
            "THB" => 'th',
            "TRY" => 'tr',
            "UAH" => 'ua',
            "GBP" => 'gb',
            "TWD" => 'tw',
            "VND" => 'vn',
            "UZS" => 'uz',
            "KZT" => 'kz',
            "TZS" => 'tz',
            "ETB" => 'et',
            "KWD" => 'kw',
            "BIF" => 'bi',
            "CDF" => 'cd',
            "NAD" => 'na',
        ];
        return isset($currencyCountryMapping[$currencyCode]) ? $currencyCountryMapping[$currencyCode] : 'unknown';
    }
}